Iter13
superles/yapmetrics pull request #12
Opened 2023-10-21 13:17 UTC by superles

2023-10-22 12:15 UTC, s-shpak requested changes

2023-10-22 12:15 UTC, s-shpak commented on internal/metric/metric.go
> +		return "", errors.New("unsupported metric type")
В подобных случаях к сообщению ошибки лучше добавлять значение, которое к этой ошибке привело

2023-10-22 12:15 UTC, s-shpak commented on internal/server/config/flags.go
> +	flag.StringVar(&config.LogLevel, "v", "error", "уровень логирования")
См. комментарий выше

2023-10-22 12:15 UTC, s-shpak commented on internal/server/config/flags.go
> +	flag.StringVar(&config.DatabaseDsn, "d", "", "интервал сохранения метрик на диск")
```suggestion
	flag.StringVar(&config.DatabaseDsn, "d", "", "<корректное-описание-флага>")
```

2023-10-22 12:15 UTC, s-shpak commented on internal/server/handlers.go
> +	defer func(Body io.ReadCloser) {
1. Сервер сам закрывает запросы: https://stackoverflow.com/questions/42525499/where-to-put-defer-req-body-close
2. переменные в го принято называть с маленькой буквы

2023-10-22 12:15 UTC, s-shpak commented on internal/server/handlers.go
> +	if err := s.storage.SetAll(context.Background(), item.ToMetrics()); err != nil {
Здесь ошибку тоже стоит залогировать

2023-10-22 12:15 UTC, s-shpak commented on internal/server/handlers.go
> +		http.Error(w, fmt.Sprintf("ошибка: %s", err), http.StatusBadRequest)
А вот клиенту ее посылать не нужно, т.к. она внутренняя. Небезопасно сообщать пользователю о внутренних ошибках сервиса

2023-10-22 12:15 UTC, s-shpak commented on internal/server/handlers.go
> +		rawBytes, _ := easyjson.Marshal(item)
Ошибки надо проверять всегда

2023-10-22 12:15 UTC, s-shpak commented on internal/server/handlers.go
> +		http.Error(w, fmt.Sprintf("ошибка конвертации метрики в json: %s", "error"), http.StatusBadRequest)
См. комментарий выше

2023-10-22 12:15 UTC, s-shpak commented on internal/server/handlers.go
> +	if true {
Тут что-то не в порядке

2023-10-22 12:15 UTC, s-shpak commented on internal/server/handlers.go
> +	dsn, _ := pgx.ParseConfig(s.config.DatabaseDsn)
Ошибки надо проверять всегда

2023-10-22 12:15 UTC, s-shpak commented on internal/server/handlers.go
> +	db, err := sql.Open("pgx", ps)
Если используешь pgx, то с БД лучше работать без использования `database/sql`. При этом пользуйся `pgxpool`

2023-10-22 12:15 UTC, s-shpak commented on internal/server/handlers.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
Мне не нравится, что ты делаешь обращение к БД и отправляешь http-ответ на одном и том же уровне. Вы обсуждали "слоенные" архитектуры?

2023-10-22 12:15 UTC, s-shpak commented on internal/server/handlers.go
> +	metricItem, ok := s.storage.Get(context.Background(), name)
Здесь лучше использовать контекст запроса

2023-10-22 12:15 UTC, s-shpak commented on internal/server/handlers.go
> +	logger.Log.Debug("GetJSONValue")
Логировать такие вещи стоит через `middleware`

2023-10-22 12:15 UTC, s-shpak commented on internal/server/handlers.go
> +func (s *Server) GetPing(w http.ResponseWriter, r *http.Request) {
Помести этот метод в интерфейс сторэджа, пусть твои сторы его реализуют

2023-10-22 12:15 UTC, s-shpak commented on internal/storage/pgstorage/pgstorage.go
> +		panic(err)
См. комментарии выше

2023-10-22 12:15 UTC, s-shpak commented on internal/storage/pgstorage/pgstorage.go
> +	db, err := sql.Open("pgx", ps)
См. комментарий выше

2023-10-22 12:15 UTC, s-shpak commented on internal/storage/pgstorage/pgstorage.go
> +SELECT id, type, value from `+tableName+`
Такое форматирование запросов приводит к риску sql-инъекции, что очень плохо. См объяснение здесь https://stackoverflow.com/questions/64170519/prevent-sql-injection-in-go-postgresql

2023-10-22 12:15 UTC, s-shpak commented on internal/storage/pgstorage/pgstorage.go
> +			if err := begin.Rollback(); err != nil {
Если будешь использовать `pgx` без `database/sql`, то сможешь работать с транзакциями более удобным способом (см. доки)

2023-10-22 12:15 UTC, s-shpak commented on internal/storage/pgstorage/pgstorage.go
> +	_, err = result.RowsAffected()
Почему ты никак не используешь возвращаемое здесь значение?

2023-10-22 13:10 UTC, superles commented on internal/storage/pgstorage/pgstorage.go
> +	_, err = result.RowsAffected()
Просто проверяю на предмет ошибки. Не придумал ничего лучше для проверки отработки скрипта

2023-10-22 13:10 UTC, superles commented on internal/storage/pgstorage/pgstorage.go
> +			if err := begin.Rollback(); err != nil {
Знаю, специально оставил database/sql для быстрой адаптации под любой SQL. Изначально был pgx

2023-10-22 13:16 UTC, superles commented on internal/storage/pgstorage/pgstorage.go
> +SELECT id, type, value from `+tableName+`
tableName - константа внутри пакета, а вот тут
```
valueStr := strconv.FormatFloat(Value, 'f', -1, 64)
	query := `
INSERT INTO ` + tableName + ` (id, type, value)
VALUES('` + Name + `',1, ` + valueStr + `)
on conflict on constraint metrics_pk
do UPDATE SET type = 1, value = ` + valueStr + `;
```
Вместо Name Может быть что угодно. Я обычно проверяю такие моменты

2023-10-22 13:51 UTC, superles commented on internal/storage/pgstorage/pgstorage.go
> +SELECT id, type, value from `+tableName+`
Не понимаю как подбросить tableName через db.Prepare

2023-10-22 14:01 UTC, superles commented on internal/storage/pgstorage/pgstorage.go
> +SELECT id, type, value from `+tableName+`
В общем нужна помощь с Prepare. Не до конца понимаю как тут работают конструкции с ? и $ и как пробросить имя таблицы(и можно ли)

2023-10-22 16:09 UTC, s-shpak commented on internal/storage/pgstorage/pgstorage.go
> +			if err := begin.Rollback(); err != nil {
Это не очень хорошая идея потому что:
1. в подавляющем большинстве случаев это никогда не потребуется
2. у тебя все равно скорее всего не придется перейти на другую БД из-за разницы в SQL-синтаксисе баз

Если проблему перехода на другую БД хотят решить, то, как правило, используют ORM, которая дает больше гарантий совместимости.

Это просто замечание, если ты не будешь это делать, то можно зарезолвить мой коммент

2023-10-22 20:02 UTC, s-shpak requested changes

2023-10-22 20:02 UTC, s-shpak commented on internal/storage/pgstorage/pgstorage.go
> +	query := fmt.Sprintf("update %s set value=%f, type=%d; where id = '%s'", tableName, data.Value, data.Type, data.Name)
И здесь тоже возможна sql-инъекция, чтобы избежать ее передавай параметры последними аргументами к `ExecContext` (или `QueryContext`)

2023-10-22 20:02 UTC, s-shpak commented on internal/storage/pgstorage/pgstorage.go
> +	_, err = result.RowsAffected()
А как именно это поможет тебе проверить правильность отработки скрипта?

2023-10-23 10:18 UTC, superles commented on internal/storage/pgstorage/pgstorage.go
> +	db, err := sql.Open("pgx", ps)
Здесь не совсем понял, но переделал на pgx dsn

2023-10-23 10:24 UTC, superles commented on internal/storage/pgstorage/pgstorage.go
> +			if err := begin.Rollback(); err != nil {
Переделал на pgxpool

2023-10-23 10:24 UTC, superles commented on internal/storage/pgstorage/pgstorage.go
> +	_, err = result.RowsAffected()
Никак, убрал

2023-10-23 10:24 UTC, superles commented on internal/storage/pgstorage/pgstorage.go
> +	query := fmt.Sprintf("update %s set value=%f, type=%d; where id = '%s'", tableName, data.Value, data.Type, data.Name)
Добавил везде pgx.Identifier{tableName}.Sanitize()

2023-10-23 10:35 UTC, superles commented on internal/storage/pgstorage/pgstorage.go
> +SELECT id, type, value from `+tableName+`
Добавил везде pgx.Identifier{tableName}.Sanitize()

2023-10-24 08:21 UTC, s-shpak requested changes
Не все комментарии закрыты

2023-10-24 08:25 UTC, superles commented on internal/agent/agent.go
> +		retry.DelayType(func(n uint, err error, config *retry.Config) time.Duration {
Да, в задании есть условие что задержки доп запросов должны быть 1с 3с 5с

2023-10-25 09:07 UTC, superles commented on internal/agent/agent.go
> +	logger.Log.Info("send request",
+

2023-10-25 09:07 UTC, superles commented on internal/agent/agent.go
> +	defer func() {
Ок

2023-10-25 09:08 UTC, superles commented on internal/agent/agent.go
> +			log.Fatal(err)
Сделал log.Error, нужно ли его поднимать выше?

2023-10-25 09:11 UTC, superles commented on internal/agent/agent.go
> +	response, postErr := retry.DoWithData(
Согласен, потянулось из каких-то правок

2023-10-25 09:19 UTC, superles commented on internal/agent/agent.go
> +	if response != nil {
Сделал

2023-10-25 09:20 UTC, superles commented on internal/agent/agent.go
> +			logger.Log.Error(readErr.Error())
Согласен. Сделал

2023-10-25 09:24 UTC, superles commented on internal/agent/agent.go
> +	if postErr != nil {
Перенес проверки на ошибку после запроса

2023-10-25 09:35 UTC, superles commented on internal/metric/json.go
> +			m.Value = *item.Value
Вот тут не совсем понял как правильно, но точно не правильно брать значение указателя который равен nil. Сделал проверку

2023-10-25 09:38 UTC, superles commented on internal/metric/metric.go
> +		return "", errors.New("unsupported metric type")
Согласен, добавил во всех случаях

2023-10-25 09:38 UTC, superles commented on internal/server/config/flags.go
> +	flag.StringVar(&config.LogLevel, "v", "error", "уровень логирования")
Сделал

2023-10-25 09:39 UTC, superles commented on internal/server/config/flags.go
> +	flag.StringVar(&config.DatabaseDsn, "d", "", "интервал сохранения метрик на диск")
Сделал

2023-10-25 09:44 UTC, superles commented on internal/server/handlers.go
> +	defer func(Body io.ReadCloser) {
Спасибо, не знал. Сделал

2023-10-25 10:01 UTC, superles commented on internal/server/handlers.go
> +		rawBytes, _ := easyjson.Marshal(item)
Добавляю проверки по всему коду

2023-10-25 10:07 UTC, superles commented on internal/server/handlers.go
> +	if true {
Да)

2023-10-25 10:13 UTC, superles commented on internal/server/handlers.go
> +	db, err := sql.Open("pgx", ps)
Исправил

2023-10-25 10:20 UTC, superles commented on internal/server/handlers.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
Нет, я пытался от предыдущих менторов получить эти рекомендации, но так и не получил. Но в целом я понял о чем речь. Добавил Ping в storage

2023-10-25 10:23 UTC, superles commented on internal/server/handlers.go
> +	metricItem, ok := s.storage.Get(context.Background(), name)
Да, я понял смысл с отменой запроса. При появлении кейса с отменой обработки запроса, тут нужно будет создавать в нужных хендлерах свой контекст с отменой. Сделал

2023-10-25 10:24 UTC, superles commented on internal/server/handlers.go
> +	logger.Log.Debug("GetJSONValue")
Да, если бы я так логировал в каждом типе запроса. Вообще убрал, это тянется с ручной отладки

2023-10-25 10:24 UTC, superles commented on internal/server/handlers.go
> +func (s *Server) GetPing(w http.ResponseWriter, r *http.Request) {
Так и понял. Сделал

2023-10-25 11:03 UTC, superles commented on cmd/agent/main.go
> +		log.Panicln("ошибка инициализации логера", err.Error())
Сделал

2023-10-25 12:16 UTC, superles commented on internal/agent/config/flags.go
> +	flag.StringVar(&config.LogLevel, "v", "error", "уровень логирования")
Понял, но оставил error, очень много логов в тестах github

2023-10-25 12:26 UTC, superles commented on internal/server/handlers.go
> +	dsn, _ := pgx.ParseConfig(s.config.DatabaseDsn)
Исправил

2023-10-25 18:49 UTC, s-shpak commented on internal/agent/agent.go
> +			log.Fatal(err)
Нет, в данном случае достаточно просто логирования, т.к. эта ошибка (пока так кажется) не требует прерывания выполнения программы

2023-10-25 18:51 UTC, s-shpak commented on internal/agent/config/flags.go
> +	flag.StringVar(&config.LogLevel, "v", "error", "уровень логирования")
А что именно генерирует много логов. Если ты наблюдаешь очень большое количество логов, то надо задуматься, можно ли его уменьшить перенеся их на debug-уровень например. По дефолту важно оставлять info - это первый уровень, информацию о котором, мы хотим видеть всегда

2023-10-25 19:17 UTC, s-shpak requested changes

2023-10-25 19:17 UTC, s-shpak commented on internal/server/handlers.go
> +		http.Error(w, "ошибка сервера", http.StatusBadRequest)
Если это ошибка сервера, то статус должен быть `500`. Можно, в принципе, оставить BadRequest, но тогда это не  "ошибка сервера"

2023-10-25 19:46 UTC, superles commented on internal/agent/agent.go
> +				if resp == nil {
При не ответе сервера resp == nil. Переделал на errors.As

2023-10-25 19:50 UTC, superles commented on internal/agent/config/flags.go
> +	flag.StringVar(&config.LogLevel, "v", "error", "уровень логирования")
Убрал логирование всех запросов в debug

2023-10-25 19:55 UTC, superles commented on internal/server/handlers.go
> +		http.Error(w, "ошибка сервера", http.StatusBadRequest)
При ошибках в условии вроде бы как нужно делать StatusBadRequest. Но по сути это не правильно. StatusInternalServerError правильнее отвечает ситуации. Я пройдусь по статусам и подправлю

2023-10-25 19:56 UTC, superles commented on internal/metric/json.go
> +			if item.Value != nil {
Понял, убрал добавление пустых значений в слайс

2023-10-25 20:21 UTC, superles commented on internal/metric/json.go
> +func (v JSONDataCollection) ToMetrics() *[]Metric {
Но я не понял, для чего мы возвращаем копию слайса, почему не вернуть указатель?

2023-10-27 10:17 UTC, s-shpak commented on internal/metric/json.go
> +func (v JSONDataCollection) ToMetrics() *[]Metric {
А зачем передавать указатель внутрь `s.Storage.SetAll` ?

Создание указателей часто приводит к боксингу значений (их перемещения из стэка в хип), что ухудшает производиттельность. Кроме того, использование указателей имеет семантическое значение (мы как бы намекаем, что будем менять объект "in-place"), но в данном случае это не так, и просто сбивает при чтении кода.

2023-10-27 10:24 UTC, s-shpak requested changes

2023-10-27 10:24 UTC, s-shpak commented on internal/storage/pgstorage/pgstorage.go
> +	begin, bErr := s.db.BeginTx(ctx, pgx.TxOptions{})
Я это проглядел, сорри.

Сейчас ты не делаешь запросы в рамках транзакции, ты делаешь их в отдельном соединении. Тебе надо использовать объект `begin` и отправлять запросы к БД через него.

Кроме того в случае батча необходимо делать не много запросов на добавление по одному значению, а записать все значения одним запросом. Здесь разбирается как это сделать:  https://stackoverflow.com/questions/70823061/bulk-insert-in-postgres-in-go-using-pgx

если без pgx, то смотри сюда: https://stackoverflow.com/questions/12486436/how-do-i-batch-sql-statements-with-package-database-sql

2023-10-27 10:24 UTC, s-shpak commented on internal/storage/pgstorage/pgstorage.go
> +	begin, bErr := s.db.BeginTx(ctx, pgx.TxOptions{})
```suggestion
	begin, err := s.db.BeginTx(ctx, pgx.TxOptions{})
```

2023-10-27 13:14 UTC, superles commented on internal/storage/pgstorage/pgstorage.go
> +	begin, bErr := s.db.BeginTx(ctx, pgx.TxOptions{})
Осталось от старого кода

2023-10-27 13:19 UTC, superles commented on internal/metric/json.go
> +func (v JSONDataCollection) ToMetrics() *[]Metric {
Я пока еще не до конца разобрался с указателями и где нужно/где нет. Но я разберусь. Пока сделал по значению

2023-10-27 13:24 UTC, superles commented on internal/storage/pgstorage/pgstorage.go
> +	begin, bErr := s.db.BeginTx(ctx, pgx.TxOptions{})
Сделал с batch. Этот вариант был у меня в коде, но задействован был старый

2023-10-28 16:05 UTC, s-shpak approved these changes

2023-10-29 11:10 UTC, merged