Iter20
superles/yapmetrics pull request #16
Opened 2024-01-19 21:37 UTC by superles

2024-01-21 10:48 UTC, gonozov0 requested changes
Отличная работа 👍
Оставил пару комментариев по улучшению кода
Я так понимаю у тебя в текущий мр попали изменения, которые касаются 21-23 инкремента. Чтобы мы с тобой не запутались и у меня не было вопросов на ревью инерементов 9-го спринта, отдели пожалуйста эти изменения в ветку iter21

2024-01-21 10:48 UTC, gonozov0 commented on internal/exitcheck/analyzer.go
Лучше вынести реализацию в pkg, т.к. это код, который может быть легко переиспользован на других проектах

2024-01-21 10:48 UTC, gonozov0 commented on internal/exitcheck/testdata/src/a/main.go
Я бы еще добавил тест на позитивный сценарий, когда линтер отрабатывает и не ругается

2024-01-24 14:38 UTC, superles commented on internal/exitcheck/analyzer.go
В pkg вынес, 21 инкремент ещё даже не открывал. Так что если вдруг пересеклось - без особого умысла)

2024-01-24 14:41 UTC, superles commented on internal/exitcheck/testdata/src/a/main.go
Сделал

2024-01-25 08:04 UTC, gonozov0 approved these changes
Работа принята 👍

2024-01-31 17:33 UTC, merged