Iter23
superles/yapmetrics pull request #17
Opened 2024-01-30 16:53 UTC by superles

2024-01-30 16:56 UTC, superles commented
Один из инкрементов был изначально. Остальные сделал на скорую руку в виду невысокой сложности

2024-01-31 14:08 UTC, gonozov0 requested changes
В данном пр-е присутствуют изменения инкрементов из предыдущего спринта
Вмержи плиз все свои прошлые пр-ы (к [примеру](https://github.com/superles/yapmetrics/pull/16)), чтобы тут остались только 21-23 инкременты

2024-02-01 08:58 UTC, gonozov0 requested changes
Все отлично выполнено по шифрованию и конфигу, но не увидел логики graceful завершения всех горутин
Как минимум [тут](https://github.com/superles/yapmetrics/pull/17/files#diff-d0706a4ae4ecf91c5224ca388f31a087a36af06c40dc81321da7958b25c70b23R115) у тебя совершенно спокойно может произойти утечка, важно добавить waitGroup и в цикле внутри самой горутины также проверять, что контекст отменен

2024-02-01 12:28 UTC, superles commented
> Все отлично выполнено по шифрованию и конфигу, но не увидел логики graceful завершения всех горутин Как минимум [тут](https://github.com/superles/yapmetrics/pull/17/files#diff-d0706a4ae4ecf91c5224ca388f31a087a36af06c40dc81321da7958b25c70b23R115) у тебя совершенно спокойно может произойти утечка, важно добавить waitGroup и в цикле внутри самой горутины также проверять, что контекст отменен

В горутинах селекты проверяют не закончен ли контекст, который в свою очередь останавливается сигналом

2024-02-02 08:36 UTC, gonozov0 commented
> > Все отлично выполнено по шифрованию и конфигу, но не увидел логики graceful завершения всех горутин Как минимум [тут](https://github.com/superles/yapmetrics/pull/17/files#diff-d0706a4ae4ecf91c5224ca388f31a087a36af06c40dc81321da7958b25c70b23R115) у тебя совершенно спокойно может произойти утечка, важно добавить waitGroup и в цикле внутри самой горутины также проверять, что контекст отменен
> 
> В горутинах селекты проверяют не закончен ли контекст, который в свою очередь останавливается сигналом

Обсудим поподробнее на 1:1

2024-02-02 08:36 UTC, gonozov0 approved these changes
Работа принята 👍

2024-02-08 13:37 UTC, merged